# Generated by Django 5.0 on 2023-12-26 16:25

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCFMCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('embedding_name', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('course_code', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuidedThesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('embedding_name', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('ucampus_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('openalex_id', models.CharField(blank=True, null=True)),
                ('openalex_works_url', models.URLField(blank=True, null=True)),
                ('rut', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FCFMCourseKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('course_code', models.CharField(max_length=100)),
                ('associated_course', models.ManyToManyField(to='teachers.fcfmcourse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuidedThesisKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('ucampus_code', models.CharField(max_length=100)),
                ('associated_thesis', models.ManyToManyField(to='teachers.guidedthesis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenAlexScholarWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('embedding_name', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('openalex_id', models.CharField(max_length=100)),
                ('abstract', models.TextField(blank=True, max_length=10000, null=True)),
                ('doi', models.CharField(blank=True, max_length=500, null=True)),
                ('teacher', models.ManyToManyField(to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='guidedthesis',
            name='teacher',
            field=models.ManyToManyField(to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='fcfmcourse',
            name='teacher',
            field=models.ManyToManyField(to='teachers.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('teacher', models.ManyToManyField(to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherScholarWorkKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('associated_work', models.ManyToManyField(to='teachers.openalexscholarwork')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
