# Generated by Django 5.0 on 2024-01-22 22:56

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCFMCourse',
            fields=[
                ('title', models.CharField(max_length=1000)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('embedding_name', pgvector.django.VectorField(dimensions=768)),
                ('course_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuidedThesis',
            fields=[
                ('title', models.CharField(max_length=1000)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('embedding_name', pgvector.django.VectorField(dimensions=768)),
                ('ucampus_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarWork',
            fields=[
                ('title', models.CharField(max_length=1000)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('embedding_name', pgvector.django.VectorField(dimensions=768)),
                ('openalex_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('abstract', models.TextField(blank=True, max_length=10000, null=True)),
                ('doi', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('rut', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('openalex_id', models.CharField(blank=True, null=True)),
                ('openalex_works_url', models.URLField(blank=True, null=True)),
                ('dblp_id', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuidedThesisKeywordRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('guided_thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.guidedthesis')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.keyword')),
            ],
            options={
                'unique_together': {('guided_thesis', 'keyword')},
            },
        ),
        migrations.AddField(
            model_name='guidedthesis',
            name='keyword',
            field=models.ManyToManyField(through='teachers.GuidedThesisKeywordRelationship', to='teachers.keyword'),
        ),
        migrations.CreateModel(
            name='FCFMCourseKeywordRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('fcfm_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.fcfmcourse')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.keyword')),
            ],
            options={
                'unique_together': {('fcfm_course', 'keyword')},
            },
        ),
        migrations.AddField(
            model_name='fcfmcourse',
            name='keyword',
            field=models.ManyToManyField(through='teachers.FCFMCourseKeywordRelationship', to='teachers.keyword'),
        ),
        migrations.CreateModel(
            name='ScholarWorkKeywordRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.keyword')),
                ('scholar_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.scholarwork')),
            ],
            options={
                'unique_together': {('scholar_work', 'keyword')},
            },
        ),
        migrations.AddField(
            model_name='scholarwork',
            name='keyword',
            field=models.ManyToManyField(through='teachers.ScholarWorkKeywordRelationship', to='teachers.keyword'),
        ),
        migrations.AddField(
            model_name='scholarwork',
            name='teacher',
            field=models.ManyToManyField(to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='guidedthesis',
            name='teacher',
            field=models.ManyToManyField(to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='fcfmcourse',
            name='teacher',
            field=models.ManyToManyField(to='teachers.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherKeywordRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.keyword')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'keyword')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='keyword',
            field=models.ManyToManyField(through='teachers.TeacherKeywordRelationship', to='teachers.keyword'),
        ),
    ]
