# Generated by Django 4.2.5 on 2023-10-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercoursekeyword',
            name='course_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
