# Generated by Django 4.2.5 on 2023-10-02 17:57

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [VectorExtension()]
