# Generated by Django 4.2.5 on 2023-10-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openalexwork',
            name='openalex_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='dblpwork',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='guidedthesis',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='openalexwork',
            name='teacher',
        ),
        migrations.AddField(
            model_name='dblpwork',
            name='teacher',
            field=models.ManyToManyField(to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='guidedthesis',
            name='teacher',
            field=models.ManyToManyField(to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='openalexwork',
            name='teacher',
            field=models.ManyToManyField(to='teachers.teacher'),
        ),
    ]
