# Generated by Django 5.0 on 2023-12-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dblp_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
