# Generated by Django 5.0 on 2024-01-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcfmcourse',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guidedthesis',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scholarwork',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
