# Generated by Django 4.2.5 on 2023-10-02 18:01

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_vector_extension_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.VectorField(dimensions=768)),
            ],
        ),
    ]
