# Generated by Django 4.2.5 on 2023-10-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teachercoursekeyword_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedthesiskeyword',
            name='ucampus_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
