# Generated by Django 5.0 on 2024-03-02 19:51

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_fcfmcourse_year_alter_guidedthesis_year_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='keyword',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='my_index', opclasses=['vector_cosine_ops']),
        ),
    ]
