# Generated by Django 5.0 on 2023-12-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_dblp_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCFMCourseKeyword',
        ),
    ]
