# Generated by Django 5.0 on 2024-03-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_keyword_my_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='keyword',
            name='my_index',
        ),
    ]
