# Generated by Django 4.2.5 on 2023-10-03 19:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_external_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAlexWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, max_length=10000, null=True)),
                ('concepts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'db_table': 'teachers_openalexworkmodel',
            },
        ),
        migrations.CreateModel(
            name='DBLPWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'db_table': 'teachers_dblpworkmodel',
            },
        ),
    ]
