# Generated by Django 4.2.5 on 2023-10-03 21:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_openalexwork_dblpwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openalexwork',
            name='concepts',
        ),
        migrations.AddField(
            model_name='openalexwork',
            name='openalex_concepts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='openalex_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
