# Generated by Django 4.2.5 on 2023-10-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_remove_openalexwork_concepts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='openalex_works_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
