# Generated by Django 4.2.5 on 2023-10-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacher_openalex_works_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblpwork',
            name='doi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openalexwork',
            name='doi',
            field=models.URLField(blank=True, null=True),
        ),
    ]
