# Generated by Django 4.2.5 on 2023-10-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_dblpwork_doi_openalexwork_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dblpwork',
            name='doi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='openalexwork',
            name='doi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
