# Generated by Django 4.2.5 on 2023-10-05 18:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_dblpwork_doi_alter_openalexwork_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='concepts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dblp_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
